# Site settings
title: lexie.photos
name: Lexie Yang
description: "lover of photography and sakura <br/> db architect at Health Catalyst"
url: "https://lexie.photos"
baseurl: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username: lexiedyang
twitter_username: lexie_dyang
instagram_username:  tobecontinue2015
email: lexiedyang@gmail.com


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "imgs/profile.jpg"

front_img: yes
front_img_path: "/imgs/background.jpg"

logo: "/imgs/profile.jpg"
cover: "/imgs/background.jpg"

# Social
name: "Lexie Yang"
author: "Lexie Yang"
twitter_handle: '@lexie_dyang'
social:
  - icon: twitter
    url: https://twitter.com/siraf
    dsec: Follow me on twitter
    share_url: https://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: github
    url: https://github.com/lexiedyang

paginate: 5
paginate_path: "/all/page:num/"

# Build settings
markdown: kramdown
permalink: /:categories/:title
gems:
  - jemoji
  - jekyll-paginate
